FROM node:20-alpine

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY . .

WORKDIR /frontend/lakaa_frontend

RUN npm cache clean --force

RUN npm install

RUN npm install -g vue-cli

RUN npm install axios@0.27.2

EXPOSE 8080

CMD ["npm", "run", "dev"]

##@## install all dependencies for the frontend using Vue CLI and Axios